nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin:
            - '^https?://(localhost|127\.0\.0\.1|portfolio\.api\.maelrabot\.com)(:\d+)?$'
            - '^https://portfolio\.api\.maelrabot\.com$'
            - '^https://portfolio\.api\.maelrabot\.com$'
            - '^https?://89\.168\.62\.189(:\d+)?$'
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            origin_regex: true
            allow_origin:
                - '^https?://(localhost|127\.0\.0\.1|portfolio\.api\.maelrabot\.com)(:\d+)?$'
                - '^https://portfolio\.api\.maelrabot\.com$'
                - '^https://portfolio\.api\.maelrabot\.com$'
                - '^https?://89\.168\.62\.189(:\d+)?$'
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Link']
            max_age: 3600

