services:
  # PHP-FPM container for Symfony
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - DATABASE_URL=mysql://${MYSQL_USER:-symfony_user}:${MYSQL_PASSWORD:-symfony_password}@database:3306/${MYSQL_DATABASE:-symfony_portfolio}?serverVersion=mariadb-${MYSQL_VERSION:-10.6}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - symfony_network

  # Nginx web server
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony_network

  # MariaDB database
  database:
    image: mariadb:10.6
    container_name: symfony_database
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-symfony_portfolio}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root_password}"]
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - symfony_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
    ports:
      - "8081:80"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - symfony_network

volumes:
  database_data:

networks:
  symfony_network:
    driver: bridge